name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python # Set Python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov

      - name: Test with pytest
        run: pytest fractulator_test.py --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml --cov=fractulator --cov-branch --cov-report=html --cov-fail-under=95

      - name: Upload pytest test results
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        if: ${{ always() }}

      - name: Upload coverage results
        uses: actions/upload-artifact@v2
        with:
          name: coverage-results-${{ matrix.python-version }}
          path: htmlcov
        if: ${{ always() }}